name: Build and deploy ASP.Net Core app to Azure Web App - dotNet0001

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Restore
        run: dotnet restore ./WebApplication1/WebApplication1.sln

      - name: Build with dotnet
        run: dotnet build ./WebApplication1/WebApplication1.sln --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish ./WebApplication1/WebApplication1.sln --configuration Release --no-build

      
